name: Convert Files in Input to Markdown

on:
  push:
    branches:
      - '*'
      - '!main'
      - '!converted'

#on: 
  #workflow_dispatch:
   # inputs:
      #input_file:
        #required: true
      #output_file:
        #required: true
        #default: "docusaurus/docs/tutorial-basics/git.md"
      

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    container:
      image: docker://pandoc/latex:2.9
      options: --entrypoint=sh
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: prepare output directories
        run: |
          for d in input/; do
            mkdir -p output/$d
          done
      - name: convert docx to md
        run: |
          find input/ -iname '*.docx' -type f -exec sh -c 'pandoc ${0} -t markdown -f docx --extract-media=. -o output/${0%.md}.md' {} \;
      #- uses: docker://pandoc/core:2.9
        #with:
#          args: --output "${{ github.event.inputs.output_file }}" -t markdown -f docx "${{ github.event.inputs.input_file }}" --extract-media=docusaurus/docs/tutorial-basics
#      - name: upload artifact
 #       uses: actions/upload-artifact@v3
  #      with:
   #       name: docx
    #      path: ${{ github.event.inputs.output_file }}
      - name: test some commands
        run: |
          SHA=`git log --pretty=format:'%H' -n 1`

          echo $SHA
          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          git config --global user.name ${{ github.actor }}
          
          git checkout -b ${{ github.run_id }} 
          git add .
          git commit -m "Convert docx to markdown"

          git push -u origin ${{ github.run_id }}

          # GitHub CLI api

          

          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/pulls \
            -f title='Add a markdown file to website' \
          -f body='Please pull these awesome changes in!' \
          -f head=${{ github.run_id }} \
          -f base='testing' 
          


        env:
          GH_TOKEN: ${{ github.token }}
        
          
          